### ISSUE TITLE
Formatting names

### ISSUE THREAD

**Issue by Xerionty** [cyberjunky/home-assistant-hvcgroep#1]
After creating a new entity card the names are shown like:

HVC Groep_gft (instead of HVC Groep GFT)
HVC Groep_papier (instead of HVC Groep Papier)
etc.

I can't rename the entities as they are read-only.

**Comment by cyberjunky** [comment]
You can use the standard home assistant customization method like this:

```yaml
homeassistant:
  customize:
    sensor.hvc_groep_restafval:
      friendly_name: 'Grijze Bak'
    sensor.hvc_groep_plastic:
      friendly_name: 'Plastic'
    sensor.hvc_groep_gft:
      friendly_name: 'Groene Bak'
    sensor.hvc_groep_papier:
      friendly_name: 'Blauwe Bak'
    sensor.afval_morgen:
      icon: mdi:trash-can-outline
    sensor.afval_vandaag:
      icon: mdi:trash-can-outline
```
